
import { WordSection } from "../types";

/**
 * 简单的 Markdown 转 HTML 解析器，专门用于 Word 导出
 * 确保 Word 能够识别标题、粗体、列表和表格
 */
function parseMarkdownToHtml(md: string): string {
  let html = md.trim();

  // 1. 处理表格 (Markdown Table to HTML Table)
  const tableRegex = /\|(.+)\|[\n\r]\|([-| :]+)\|[\n\r]((?:\|.+\|[\n\r]*)+)/g;
  html = html.replace(tableRegex, (match, header, divider, rows) => {
    const headers = header.split('|').filter((h: string) => h.trim()).map((h: string) => `<th style="border:1px solid #CBD5E1; padding:8px; background-color:#F8FAFC; text-align:left;">${h.trim()}</th>`).join('');
    const bodyRows = rows.trim().split('\n').map((row: string) => {
      const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td style="border:1px solid #CBD5E1; padding:8px;">${c.trim()}</td>`).join('');
      return `<tr>${cells}</tr>`;
    }).join('');
    return `<table style="border-collapse:collapse; width:100%; margin-bottom:16pt; font-family:sans-serif; font-size:10pt;"><thead><tr style="background-color:#F1F5F9;">${headers}</tr></thead><tbody>${bodyRows}</tbody></table>`;
  });

  // 2. 处理标题 (H1, H2, H3)
  html = html.replace(/^# (.+)$/gm, '<h1 style="color:#1E293B; font-family:sans-serif; font-size:18pt; margin-top:20pt; border-bottom:1pt solid #E2E8F0; padding-bottom:4pt;">$1</h1>');
  html = html.replace(/^## (.+)$/gm, '<h2 style="color:#4F46E5; font-family:sans-serif; font-size:14pt; margin-top:16pt;">$1</h2>');
  html = html.replace(/^### (.+)$/gm, '<h3 style="color:#0F172A; font-family:sans-serif; font-size:12pt; margin-top:12pt;">$1</h3>');

  // 3. 处理粗体
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');

  // 4. 处理引用
  html = html.replace(/^> (.+)$/gm, '<div style="border-left:4pt solid #6366F1; background-color:#F5F3FF; padding:10pt; margin:10pt 0; color:#4338CA; font-style:italic;">$1</div>');

  // 5. 处理无序列表
  html = html.replace(/^\- (.+)$/gm, '<li style="margin-bottom:4pt;">$1</li>');
  // 包装 <li> 标签到 <ul>
  html = html.replace(/((?:<li.*?>.*?<\/li>\n?)+)/g, '<ul style="margin-bottom:12pt;">$1</ul>');

  // 6. 处理换行 (将剩余的单换行转换为 <p>)
  const paragraphs = html.split('\n\n');
  html = paragraphs.map(p => {
    if (p.trim().startsWith('<')) return p; // 已经是 HTML 标签的跳过
    return `<p style="margin-bottom:10pt; line-height:1.6; color:#334155;">${p.replace(/\n/g, '<br/>')}</p>`;
  }).join('');

  return html;
}

export function exportToWord(sections: WordSection[], fileName: string = "CaseLens_Expert_Dossier"): void {
  const htmlHeader = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head><meta charset='utf-8'><title>Professional Case Analysis</title>
    <style>
      @page { 
        margin: 1.0in; 
      }
      body { 
        font-family: 'Segoe UI', 'Arial', sans-serif; 
        line-height: 1.5; 
        color: #0F172A; 
      }
      .footer {
        font-size: 9pt;
        color: #94A3B8;
        border-top: 1pt solid #E2E8F0;
        margin-top: 40pt;
        padding-top: 10pt;
      }
    </style>
    </head><body>
    <div style="text-align:center; margin-bottom:30pt;">
      <h1 style="font-size:24pt; color:#4F46E5; margin-bottom:0;">CaseLens Pro</h1>
      <p style="font-size:10pt; color:#64748B; text-transform:uppercase; letter-spacing:2pt;">Confidential Legal Expert Dossier</p>
    </div>
  `;

  const htmlFooter = `
    <div class="footer">
      Generated by CaseLens Pro AI - European Privacy Compliance Expert System. 
      This document is for strategic advisory purposes only.
    </div>
    </body></html>
  `;
  
  let content = "";
  sections.forEach(section => {
    const renderedContent = parseMarkdownToHtml(section.content);
    content += `
      <div style="margin-bottom:40pt;">
        <div style="background-color:#F8FAFC; padding:10pt; border-left:5pt solid #1E293B; margin-bottom:15pt;">
          <span style="font-size:9pt; font-weight:bold; color:#64748B; text-transform:uppercase;">Section: ${section.title}</span>
        </div>
        ${renderedContent}
      </div>
    `;
  });

  const fullHtml = htmlHeader + content + htmlFooter;
  
  // Word 识别 HTML 转换所需的 Blob 设置
  const blob = new Blob(['\ufeff', fullHtml], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${fileName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
